# Generated by Django 3.1.5 on 2021-01-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metal', '0002_auto_20210117_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
