# Generated by Django 3.1.5 on 2021-01-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Metal', '0003_comments_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
