# Generated by Django 3.1.5 on 2021-01-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metal', '0004_auto_20210117_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['data']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Редактор', max_length=200, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
